### PR TITLE
Add Av2 license file

### PR DESCRIPTION
**Pull request by desktophero**
Looking to possibly use this and contribute some updates ... but want to make sure the right license is in place first.

### CODE REVIEW

**Comment by TraGicCode** [comment]
Since this is license related I will make this change tonight.  Thank you

**Comment by desktophero** [comment]
And if Av2 isn't the right one you want, cool. I am more than happy to push a different one.

**Comment by desktophero** [comment]
@TraGicCode ... good day. Just circling back on this PR to see if you're good with a merge or looking for some other option. Thank you!

**Comment by TraGicCode** [comment]
Hey @desktophero ,

Doing this now.

**Comment by TraGicCode** [comment]
Hey @desktophero ,

Let me know if anything else requires attention.  Thanks!

**Pull request closed without merging**
